const primeExampleOutput = [
    "",
    "",
    "<Code filePath=\"./src/math/utils/fibonacci.ts\">",
    "export const primeNumber = (a: number): boolean => {",
    "  if (a <= 1) return false;",
    "  for (let i = 2; i < a; i++) {",
    "    if (a % i === 0) return false;",
    "  }",
    "  return true;",
    "};",
    "</Code>",
    "",
    "<WorkDescription filePath=\"./src/math/utils/fibonacci.ts\">",
    "I created a new file called 'fibonacci.ts' in the directory ./src/math/utils/. This file contains a function called 'primeNumber' which takes an integer greater than 0 and returns true if the number is prime, false otherwise. I wrote the code for the function using a for loop to check if the number is divisible by any number between 2 and the number itself.",
    "",
    "I also created a corresponding file in the test server code using typescript, mocha, and chai, that provides test coverage for the code I wrote.",
    "",
    "No external libraries were used.",
    "</WorkDescription>",
  ]